AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for lazy-home

Globals:
  Function:
    Timeout: 10
    Handler: app.lambda_handler
    Runtime: python3.9
    Architectures:
      - x86_64
    Layers:
      - !Ref LazyHomeLayer
    Environment:
      Variables:
        CHANNEL_ACCESS_TOKEN: !Ref channelAccessToken
        ADMIN_LINE_USER_ID: !Ref adminLineUserId

Parameters:
  channelAccessToken:
    Type: String
    Description: line bot channel access token
  adminLineUserId:
    Type: String
    Description: notification destination line user id

Resources:
  LazyHomeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  ControllerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/controller/
      Events:
        Controller:
          Type: Api
          Properties:
            Path: /controller
            Method: post
      FunctionName: ControllerFunc

  ControllerFuncLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - ControllerFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${ControllerFunction}
      RetentionInDays: 7

  WakeUpTimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/routine/morning/wake_up_time/
      FunctionName: WakeUpTimeFunc

  WakeUpTimeFuncLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - WakeUpTimeFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${WakeUpTimeFunc}
      RetentionInDays: 7

  OpenCurtainsStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: OpenCurtainsStateMachine
      Type: STANDARD
      DefinitionUri: statemachine/open_curtains.asl.yaml
      DefinitionSubstitutions:
        WakeUpTimeFunctionArn: !GetAtt WakeUpTimeFunction.Arn
      Events:
        Execute:
          Type: Schedule
          Properties:
            Schedule: cron(0 15 * * ? *) # 毎日24:00(JST)
