AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for lazy-home

Globals:
  Function:
    Timeout: 10
    Handler: app.lambda_handler
    Runtime: python3.9
    Architectures:
      - x86_64
    Layers:
      - !Ref LazyHomeLayer
    Environment:
      Variables:
        CHANNEL_ACCESS_TOKEN: !Ref channelAccessToken
        ADMIN_LINE_USER_ID: !Ref adminLineUserId

Parameters:
  channelAccessToken:
    Type: String
    Description: line bot channel access token
  adminLineUserId:
    Type: String
    Description: notification destination line user id

Resources:
  LazyHomeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/hello_world/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  ControllerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/controller/
      Events:
        Controller:
          Type: Api
          Properties:
            Path: /controller
            Method: post
      FunctionName: ControllerFunc

  ControllerFuncLogGroup:
      Type: AWS::Logs::LogGroup
      DependsOn: ControllerFunction
      Properties:
        LogGroupName: !Sub /aws/lambda/${ControllerFunction}
        RetentionInDays: 7