AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for lazy-home

Globals:
  Function:
    Timeout: 10
    Handler: app.lambda_handler
    Runtime: python3.9
    Architectures:
      - x86_64
    Layers:
      - !Ref LazyHomeLayer
    Environment:
      Variables:
        CHANNEL_ACCESS_TOKEN: !Ref ChannelAccessToken
        ADMIN_LINE_USER_ID: !Ref AdminLineUserId

Parameters:
  ChannelAccessToken:
    Type: String
    Description: line bot channel access token
  AdminLineUserId:
    Type: String
    Description: notification destination line user id

Resources:
  LazyHomeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  ControllerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/controller/
      Events:
        Controller:
          Type: Api
          Properties:
            Path: /controller
            Method: post
      FunctionName: ControllerFunc

  ControllerFuncLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - ControllerFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${ControllerFunction}
      RetentionInDays: 7

  WakeUpTimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/routine/morning/wake_up_time/
      FunctionName: WakeUpTimeFunc

  WakeUpTimeFuncLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - WakeUpTimeFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${WakeUpTimeFunction}
      RetentionInDays: 7

  OpenCurtainsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/routine/morning/open_curtains/
      FunctionName: OpenCurtainsFunc

  OpenCurtainsFuncLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - OpenCurtainsFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${OpenCurtainsFunction}
      RetentionInDays: 7

  OpenCurtainsStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: OpenCurtainsStateMachine
      Type: STANDARD
      DefinitionUri: statemachine/open_curtains.asl.yaml
      DefinitionSubstitutions:
        WakeUpTimeFunctionArn: !GetAtt WakeUpTimeFunction.Arn
        OpenCurtainsFunctionArn: !GetAtt OpenCurtainsFunction.Arn
      Events:
        Execute:
          Type: Schedule
          Properties:
            Schedule: cron(0 15 * * ? *) # 毎日24:00(JST)
      Role: !GetAtt StateMachineRole.Arn
      Logging:
        Level: ALL
        IncludeExecutionData: True
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt OpenCurtainsStateMachineLogGroup.Arn

  OpenCurtainsStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName : /aws/states/OpenCurtainsStateMachine

  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: >-
        Permissions required to execute step functions
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess