AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lazy-home

  Sample SAM Template for lazy-home

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  channelAccessToken:
    Type: String
    Description: line bot channel access token
  adminLineUserId:
    Type: String
    Description: notification destination line user id

Resources:
  LazyHomeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  ControllerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/controller/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Controller:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /controller
            Method: post
      Environment:
        Variables:
          CHANNEL_ACCESS_TOKEN: !Ref channelAccessToken
          ADMIN_LINE_USER_ID: !Ref adminLineUserId
      Layers:
        - !Ref LazyHomeLayer
      FunctionName: ControllerFunc

  ControllerFuncLogGroup:
      Type: AWS::Logs::LogGroup
      DependsOn: ControllerFunction
      Properties:
        LogGroupName: !Sub /aws/lambda/${ControllerFunction}
        RetentionInDays: 30