name: Deploy application

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # clean up artifact
      - run: aws s3 rm s3://${{ secrets.S3_ARTIFACT_BUCKET_NAME }} --recursive --quiet

      # sam build
      - run: sam build --use-container

      # Run Unit tests- Specify unit tests here
      - run : pip install -r tests/requirements.txt
      - run: pytest -s -k test_lambda_handler

      # sam deploy
      - run: >
          sam deploy
          --no-confirm-changeset
          --no-fail-on-empty-changeset
          --stack-name lazy-home
          --s3-bucket lazy-home-build-source
          --capabilities CAPABILITY_IAM
          --region ap-northeast-1
          --parameter-overrides \
              ChannelAccessToken=${{ secrets.CHANNEL_ACCESS_TOKEN }} \
              AdminLineUserId=${{ secrets.ADMIN_LINE_USER_ID }} \
              TwitterConsumerSecret=${{ secrets.TWITTER_CONSUMER_SECRET }}